{% set name = "ff3" %}
{% set version = "1.0.0" %}


package:
  name: python-fpe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ff3-{{ version }}.tar.gz
  sha256: 3c8ffc0ac9205850514860ce8cdea90535e45f8789187234e4fdbe9572a6f2dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pycryptodome
    - python >=3.6

test:
  imports:
    - ff3
  commands:
    - pip check
    # - python3 -m ff3.ff3_test
  requires:
    - pip

about:
  home: https://github.com/mysto/python-fpe
  summary: Format Preserving Encryption (FPE) with FF3
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bschoening
    - maresb
