{% set name = "ff3" %}
{% set version = "1.0.2" %}


package:
  name: python-fpe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ff3-{{ version }}.tar.gz
  sha256: ff892c7472509c17f68cb4907f8af7fc91835cb68c260e2ab7597b57ad44bc7a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - pycryptodome
    - python >=3.8

test:
  imports:
    - ff3
  commands:
    - pip check
    - python3 -m ff3.ff3_test
  requires:
    - pip

about:
  home: https://github.com/mysto/python-fpe
  summary: Format Preserving Encryption (FPE) with FF3
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bschoening
    - maresb
